name = "FastUnitfulOperations"
uuid = "b031420d-871e-4e9c-8878-33bec386257e"
authors = ["Lucas Valenzuela"]
version = "0.1.0"

[deps]
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
